name: Test Terraform

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository files
        run: |
          echo "Listing all files in the repository after checkout:"
          ls -R