name: Terraform CI/CD

on: push


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Terraform Init-1
        working-directory: C:/Sudhakar/Learn/0001-AWS/06-Docker/03-Python-Django-Project1/Terraform/deploy_on_ec2/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: C:/Sudhakar/Learn/0001-AWS/06-Docker/03-Python-Django-Project1/Terraform/deploy_on_ec2/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: C:/Sudhakar/Learn/0001-AWS/06-Docker/03-Python-Django-Project1/Terraform/deploy_on_ec2/terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}