name: Test Terraform

on:
  push:
    branches:
      - main  # Adjust the branch as per your requirement

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false  # Ensure terraform_wrapper is set to false    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./TerraformScripts

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./TerraformScripts

      - name: Apply Terraform
        run: terraform apply --auto-approve
        working-directory: ./TerraformScripts

      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: ./TerraformScripts  # Adjust the path to your Terraform configuration directory

      - name: Display Public IP
        run: |
          echo "Public IP Address: ${{ steps.tf-outputs.outputs.web_server_public_ip }}"
        
 

      - name: Wait for 2 minutes
        run: sleep 120

      # Add finally block to ensure destroy step is always executed
      - name: Clean up Terraform
        if: always()  # Ensure this step runs regardless of previous steps
        run: terraform destroy --auto-approve
        working-directory: ./TerraformScripts