name: 02- Events - Push,pull,cron,dispatch
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
    #push:
    pull_request:
    #schedule:
        #- cron: '*/5 * * * *'
    workflow_dispatch:
    
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - name: show the trigger 
          run: echo "This got triggered by the following event that is  ${{ github.event_name }}"
 