name: 06 - Context


on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "workflow"


jobs:
  context-sample:
    runs-on: ubuntu-latest
    env:
        MY_JOB_VAR: 'job'
        MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Context Values
        run: |
          echo "Event Name ${{ github.event_name }}"
          echo "Ref ${{ github.ref }}"
          echo "SHA ${{ github.sha }}"
          echo "Actor ${{ github.actor }}"
          echo "Workflow ${{ github.workflow }}"
          echo "RunId ${{ github.run_id }}"
          echo "Run number ${{ github.run_number }}"
      - name: Retrieve Variables
        run: |
          echo "Variable value: ${{ vars.my_var }}"
      - name: Retrive Env Varaible
        run: |
          echo "Env Variabel is ${{env.MY_WORKFLOW_VAR}}"
          echo "Evn Variable Overrided is ${{env.MY_OVERWRITTEN_VAR}}"
